import React, {useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {subjects, questions, sourcesNote} from './data/content';
import './styles.css';

const storeKey='physics-ai-v2';
const defaults={progress:{},notes:{},diagrams:{}};
const load=()=>{try{return {...defaults,...JSON.parse(localStorage.getItem(storeKey)||'{}')}}catch{return defaults}};
const save=s=>localStorage.setItem(storeKey,JSON.stringify(s));

function App(){
 const subject=subjects[0]; const [state,setState]=useState(load); const [chapterId,setChapterId]=useState('p1'); const [tab,setTab]=useState('learn'); const [search,setSearch]=useState('');
 const chapter=subject.chapters.find(x=>x.id===chapterId)||subject.chapters[0];
 const chapters=subject.chapters.filter(c=>(`${c.no} ${c.title} ${c.focus}`).toLowerCase().includes(search.toLowerCase()));
 const update=(partial)=>{const n={...state,...partial};setState(n);save(n)};
 const toggleDone=()=>update({progress:{...state.progress,[chapter.id]:!state.progress[chapter.id]}});
 const completion=Math.round(Object.values(state.progress).filter(Boolean).length/subject.chapters.length*100);
 return <div className="app">
   <header className="topbar"><div className="brand"><div className="logo">∿</div><div><b>Physics 9–10</b><span>AI Learning Hub 2.0</span></div></div><div className="header-right"><div className="progress-chip">Progress <b>{completion}%</b></div><div className="search"><span>⌕</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Chapter / concept খুঁজুন..."/></div><button className="dark-btn" onClick={()=>setTab('practice')}>Practice Zone</button></div></header>
   <div className="layout"><aside className="sidebar"><div className="side-label">SUBJECT</div><div className="subject-card active"><span className="subject-icon">⚛</span><div><b>পদার্থবিজ্ঞান</b><small>নবম–দশম</small></div><strong>{subject.chapters.length}</strong></div><div className="side-label">CHAPTERS</div><div className="chapter-list">{chapters.map(c=><button key={c.id} className={`chapter ${c.id===chapter.id?'active':''}`} onClick={()=>{setChapterId(c.id);setTab('learn')}}><span className="num">{String(c.no).padStart(2,'0')}</span><span><b>{c.title}</b><small>{c.focus}</small></span>{state.progress[c.id]&&<i>✓</i>}</button>)}</div><div className="sidebar-foot"><span className="live-dot"/> AI Tutor ready</div></aside>
   <main className="main"><section className="hero"><div><div className="eyebrow">CHAPTER {chapter.no} • STUDENT ROADMAP</div><h1>{chapter.title}</h1><p>{chapter.focus}</p></div><button className={state.progress[chapter.id]?'done-btn':'primary-btn'} onClick={toggleDone}>{state.progress[chapter.id]?'✓ Learned':'Mark as learned'}</button></section>
    <nav className="tabs"><button className={tab==='learn'?'active':''} onClick={()=>setTab('learn')}>Learn</button><button className={tab==='diagram'?'active':''} onClick={()=>setTab('diagram')}>Diagram Board</button><button className={tab==='practice'?'active':''} onClick={()=>setTab('practice')}>Practice</button><button className={tab==='ai'?'active':''} onClick={()=>setTab('ai')}>Live AI Tutor</button></nav>
    {tab==='learn'&&<Learn chapter={chapter}/>} {tab==='diagram'&&<DiagramBoard chapter={chapter} state={state} update={update}/>} {tab==='practice'&&<Practice chapter={chapter} allQuestions={questions}/>} {tab==='ai'&&<AITutor chapter={chapter}/>} 
   </main></div>
 </div>
}

function Learn({chapter}){return <div className="learn-grid"><section className="panel manual"><div className="panel-head"><div><span className="kicker">TEACHER / STUDENT MANUAL</span><h2>এই chapter শুরুর আগে কী কী পড়বে?</h2></div><span className="badge">{chapter.manual.length} goals</span></div><div className="manual-list">{chapter.manual.map((x,i)=><div key={i}><span>{i+1}</span><p>{x}</p><input type="checkbox"/></div>)}</div></section><section className="panel concepts"><div className="panel-head"><div><span className="kicker">ALL CORE CONCEPTS</span><h2>Concept-by-concept learning</h2></div><span className="badge">{chapter.concepts.length} concepts</span></div>{chapter.concepts.map((c,i)=><article className="concept-card" key={c.title}><div className="concept-index">{String(i+1).padStart(2,'0')}</div><div className="concept-body"><h3>{c.title}</h3><p>{c.text}</p><div className="formula"><span>সূত্র</span><code>{c.formula}</code></div><div className="concept-footer"><span><b>Exam focus:</b> {c.exam}</span><span><b>Common mistake:</b> {c.mistake}</span></div></div></article>)}</section><QuestionPanel chapter={chapter}/><section className="panel import-panel"><div className="panel-head"><div><span className="kicker">QUESTION IMPORT</span><h2>৬ বছরের Board + School প্রশ্ন যোগ করো</h2></div></div><p>{sourcesNote}</p><ImportQuestions/></section></div>}

function QuestionPanel({chapter}){const qs=questions.filter(q=>q.chapter===chapter.id).sort((a,b)=>b.importance-a.importance||b.year-a.year);return <section className="panel question-panel"><div className="panel-head"><div><span className="kicker">QUESTIONS ATTACHED TO CONCEPTS</span><h2>এই chapter-এর প্রশ্ন + solve</h2></div><span className="badge">{qs.length} sample</span></div><div className="question-list">{qs.map(q=><QuestionCard q={q} key={q.id}/>)}</div></section>}
function QuestionCard({q}){const [open,setOpen]=useState(false);return <article className="qcard"><div className="qmeta"><span>{q.year}</span><span>{q.source}</span><span>{q.type}</span><span>{q.concept}</span><span>{'★'.repeat(q.importance)}</span></div><h3>{q.q}</h3>{q.options&&<div className="options">{q.options.map(o=><button key={o}>{o}</button>)}</div>}<button className="solution-btn" onClick={()=>setOpen(!open)}>{open?'Solution hide':'Solution দেখুন'}</button>{open&&<div className="solution"><b>Answer:</b> {q.answer}<br/><span>{q.solution}</span></div>}</article>}

function Practice({chapter,allQuestions}){const [scope,setScope]=useState('all');const [type,setType]=useState('all');const [year,setYear]=useState('all');const qs=allQuestions.filter(q=>(scope==='all'||q.chapter===chapter.id)&&(type==='all'||q.type===type)&&(year==='all'||String(q.year)===year)).sort((a,b)=>b.importance-a.importance||b.year-a.year);return <div className="practice-wrap"><section className="practice-banner"><div><span className="eyebrow">PRACTICE ZONE</span><h1>{scope==='all'?'সব chapter-এর':'Chapter '+chapter.no+'-এর'} important প্রশ্ন</h1><p>Importance → year → difficulty অনুযায়ী সাজানো। প্রতিটি প্রশ্নের শেষে solution আছে।</p></div><div className="filters"><select value={scope} onChange={e=>setScope(e.target.value)}><option value="all">All chapters</option><option value="current">Current chapter</option></select><select value={type} onChange={e=>setType(e.target.value)}><option value="all">All types</option><option value="MCQ">MCQ</option><option value="CQ">CQ</option></select><select value={year} onChange={e=>setYear(e.target.value)}><option value="all">All years</option>{[2025,2024,2023,2022,2021,2020].map(y=><option key={y} value={y}>{y}</option>)}</select></div></section><div className="practice-list">{qs.map(q=><QuestionCard key={q.id} q={q}/>)}</div><div className="note-box">বর্তমান bundle-এ teaching/sample questions আছে। আসল ৬ বছরের complete question set ঢোকাতে Import Questions দিয়ে তোমার verified board/school question file import করো।</div></div>}

function ImportQuestions(){const [msg,setMsg]=useState('');const change=e=>{const file=e.target.files?.[0];if(!file)return;const r=new FileReader();r.onload=()=>{try{const parsed=JSON.parse(r.result);if(!Array.isArray(parsed))throw new Error();localStorage.setItem('physics-imported-questions',JSON.stringify(parsed));setMsg(`${parsed.length}টি question import হয়েছে (browser-local).`)}catch{setMsg('JSON format ঠিক নয়। উদাহরণ নিচে README-তে দেওয়া আছে।')}};r.readAsText(file)};return <div className="import-box"><label className="file-btn">JSON Question File বাছাই<input type="file" accept="application/json" onChange={change}/></label>{msg&&<span>{msg}</span>}<small>Fields: id, chapter, year, source, type, difficulty, importance, concept, q, options?, answer, solution</small></div>}

function DiagramBoard({chapter,state,update}){const d=state.diagrams[chapter.id]||{label:'বস্তু',value1:'2',value2:'6',unit1:'kg',unit2:'N'};const set=(k,v)=>update({diagrams:{...state.diagrams,[chapter.id]:{...d,[k]:v}}});return <div className="diagram-page"><section className="panel diagram-panel"><div className="panel-head"><div><span className="kicker">LIVE EDITABLE BOARD</span><h2>{chapter.title} — diagram lab</h2></div><span className="badge">Live</span></div><div className="diagram-stage"><DiagramSVG type={chapter.diagram} d={d}/></div><div className="controls"><label>Label<input value={d.label} onChange={e=>set('label',e.target.value)}/></label><label>Value 1<input value={d.value1} onChange={e=>set('value1',e.target.value)}/></label><label>Value 2<input value={d.value2} onChange={e=>set('value2',e.target.value)}/></label><label>Unit 1<input value={d.unit1} onChange={e=>set('unit1',e.target.value)}/></label><label>Unit 2<input value={d.unit2} onChange={e=>set('unit2',e.target.value)}/></label></div><p className="board-help">Input বদলালেই diagram live update হবে। Teacher demo, self-study এবং screenshot-এর জন্য ব্যবহার করতে পারবে।</p></section></div>}
function DiagramSVG({type,d}){const arrow=<marker id="arr" markerWidth="9" markerHeight="9" refX="8" refY="3" orient="auto"><path d="M0 0 L9 3 L0 6Z"/></marker>; if(type==='motion')return <svg viewBox="0 0 800 360"><defs>{arrow}</defs><line x1="70" y1="280" x2="740" y2="280" className="axis"/><polyline points="90,245 220,200 360,170 520,95 700,60" className="curve"/><text x="95" y="320">time (t)</text><text x="600" y="45">motion graph</text></svg>; if(type==='wave')return <svg viewBox="0 0 800 300"><defs>{arrow}</defs><path d="M50 155 C100 55 160 255 210 155 S320 55 370 155 S480 255 530 155 S640 55 750 155" className="curve"/><line x1="210" y1="245" x2="530" y2="245" className="arrowline" markerEnd="url(#arr)"/><text x="330" y="275">λ = {d.value1}</text><text x="55" y="35">wave</text></svg>; if(type==='circuit')return <svg viewBox="0 0 800 340"><defs>{arrow}</defs><line x1="150" y1="90" x2="620" y2="90" className="wire"/><line x1="150" y1="250" x2="620" y2="250" className="wire"/><line x1="150" y1="90" x2="150" y2="250" className="wire"/><line x1="620" y1="90" x2="620" y2="250" className="wire"/><rect x="340" y="65" width="100" height="50" className="component"/><text x="355" y="98">R={d.value1}Ω</text><line x1="300" y1="90" x2="260" y2="90" className="arrowline" markerEnd="url(#arr)"/><circle cx="150" cy="170" r="45" className="component"/><text x="128" y="177">{d.value2} V</text></svg>; if(type==='lens'||type==='mirror')return <svg viewBox="0 0 800 360"><defs>{arrow}</defs><line x1="80" y1="280" x2="720" y2="280" className="axis"/><line x1="410" y1="70" x2="410" y2="300" className="axis"/><path d={type==='lens'?'M410 90 Q450 175 410 260 Q370 175 410 90':'M410 90 Q360 175 410 260'} className="optical"/><line x1="120" y1="210" x2="360" y2="175" className="arrowline" markerEnd="url(#arr)"/><line x1="460" y1="175" x2="690" y2="140" className="arrowline" markerEnd="url(#arr)"/><text x="85" y="55">{type==='lens'?'Convex lens':'Concave mirror'}</text><text x="105" y="330">u = {d.value1}</text><text x="560" y="330">v = {d.value2}</text></svg>; if(type==='force')return <svg viewBox="0 0 800 330"><defs>{arrow}</defs><rect x="335" y="125" width="130" height="75" rx="10" className="component"/><text x="380" y="168">{d.label}</text><line x1="400" y1="125" x2="400" y2="55" className="arrowline" markerEnd="url(#arr)"/><text x="420" y="70">F={d.value2} N</text><line x1="335" y1="165" x2="190" y2="165" className="arrowline" markerEnd="url(#arr)"/><text x="180" y="145">friction</text></svg>; return <svg viewBox="0 0 800 330"><defs>{arrow}</defs><line x1="80" y1="250" x2="720" y2="250" className="axis"/><rect x="320" y="155" width="150" height="70" className="component"/><text x="350" y="198">{d.label}</text><line x1="395" y1="155" x2="395" y2="80" className="arrowline" markerEnd="url(#arr)"/><text x="415" y="95">{d.value1} {d.unit1}</text><text x="330" y="290">{d.value2} {d.unit2}</text></svg>}

function AITutor({chapter}){const [messages,setMessages]=useState([{role:'assistant',text:`আমি “${chapter.title}” chapter-এর AI tutor। Concept, formula, numerical, CQ/MCQ—যেকোনো প্রশ্ন করো।`}]);const [text,setText]=useState('');const [loading,setLoading]=useState(false);const send=async()=>{const q=text.trim();if(!q)return;setText('');setMessages(m=>[...m,{role:'user',text:q}]);setLoading(true);try{const r=await fetch('/api/tutor',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question:q,chapter:chapter.title,focus:chapter.focus,concepts:chapter.concepts.map(x=>x.title)})});const data=await r.json();setMessages(m=>[...m,{role:'assistant',text:data.answer||data.error||'উত্তর পাওয়া যায়নি।'}])}catch{setMessages(m=>[...m,{role:'assistant',text:'AI server পাওয়া যায়নি। API key/configuration check করো।'}])}finally{setLoading(false)}};return <section className="ai-page"><div className="ai-banner"><div><span className="eyebrow">LIVE AI TUTOR</span><h1>Real-time doubt solving</h1><p>Context: {chapter.title}</p></div><span className="online">● ONLINE</span></div><div className="chat">{messages.map((m,i)=><div key={i} className={`msg ${m.role==='user'?'user':''}`}><div className="avatar">{m.role==='user'?'YOU':'AI'}</div><div className="bubble">{m.text}</div></div>)}{loading&&<div className="msg"><div className="avatar">AI</div><div className="bubble">ভাবছি…</div></div>}</div><div className="chatbar"><input value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()} placeholder="যেমন: momentum আর force-এর relation বুঝাও"/><button onClick={send}>Send ↗</button></div></section>}

createRoot(document.getElementById('root')).render(<App/>);
